### ISSUE TITLE
Website not rendering template examples

### ISSUE THREAD

**Issue by tschaub** [rantav/go-archetype#17]
Maybe this is known, but when the project readme is rendered at https://go-archetype.dev/, all of the template examples (e.g. `{{ .ProjectName }}`) are rendered as double backticks (``` `` ```) or are missing altogether.

Example from the website
![image](https://user-images.githubusercontent.com/41094/162272357-a8d0f176-5ec3-4959-a9d5-61a153fc6d6e.png)

And the same section on GitHub
![image](https://user-images.githubusercontent.com/41094/162272431-54fa9b92-985c-4dec-a525-9c5d40b78eda.png)

**Comment by titusjaka** [comment]
Hi 👋

Thank you for reporting the issue.
I'll try to fix it shortly.

**Comment by titusjaka** [comment]
Haha, it was easier than I thought.
Fixed in #18.
