### ISSUE TITLE
go-archetype  copies full path from source

### ISSUE THREAD

**Issue by olegsu** [rantav/go-archetype#3]
Hey @rantav, 
I was trying to run `go-archetype` from a different directory of the template project one, passing the full path to the transformations flag and to the source flag. The result is that it copies all the content of the source to the destination.
I am not sure whenever I am doing something wrong, or what should be the solution in that case, as if we copy only the file, dropping all the prefix path, we may ignore a required structure of a project.

Here's an example:
```bash
mkdir new-project
cd new-project
go-archetype transform --transformations=$HOME/workspace/template-project/transformatil.yaml --source=$HOME/workspace/template-project/transformatil.yaml --destination=.
```
The result is that the destination now have the full tree of `$HOME/workspace/template-project`, also the transformation didn't ignore stuff like `.git`

I looked on a different project [boilr](https://github.com/tmrts/boilr) they are using a kind of repository concept, where the base path comes from the repository. I find it very useful, worth consideration.
What do you think?

**Comment by rantav** [comment]
Hi Oleg, thanks for the feedback. go-archetype indeed copies the entire tree (on purpose) except the ignored files. 
So typically you'd start your `transformations.yml` file like that: 

```yml
ignore:
  - .git/
  - transformations.yml
```

Does that help?

**Comment by olegsu** [comment]
@rantav thanks for the quick response, actually it doesn't help.
I recorded it, maybe I am doing something wrong?
[![asciicast](https://asciinema.org/a/DFgvqtU9Md5QlELaYWgtwZImr.svg)](https://asciinema.org/a/DFgvqtU9Md5QlELaYWgtwZImr)

**Comment by rantav** [comment]
alright. I see the issue, happens when source path is relative, fixing it, thanks for your report!

**Comment by rantav** [comment]
Fixed in https://github.com/rantav/go-archetype/releases/tag/v0.1.4

**Comment by olegsu** [comment]
Thank you @rantav
